organization:
  name: default
database:
  url: postgresql://postgres:pwd@postgres/postgres
clusters:
  - id: avien-kafka
    name: aiven-kafka
    color: '#0013E7'
    bootstrapServers: '$MANAGED_KAFKA_BOOTSTRAP_SERVERS'
    properties: |
        security.protocol=SSL
        ssl.truststore.location=/security/client.truststore.jks
        ssl.truststore.password=${TRUSTSTORE_PASSWORD}
        ssl.keystore.type=PKCS12
        ssl.keystore.location=/security/client.keystore.p12
        ssl.keystore.password=${KEYSTORE_PASSWORD}
        ssl.key.password=${KEY_PASSWORD}
admin:
  email: admin@demo.dev
  password: adminP4ss!